version: 2
jobs:
   build:
     working_directory: ~/group4_FinalProject
     docker:
       - image: circleci/php:5.6-node-browsers
     steps:
      - checkout
      # restore_cache:
      #   key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: PHPUnit setup
          command: |
            wget https://phar.phpunit.de/phpunit-5.7.phar
            chmod +x phpunit-5.7.phar
            sudo mv phpunit-5.7.phar /usr/local/bin/phpunit
            phpunit --version
            
      # save_cache:
      #   key: dependency-cache-{{ checksum "package.json" }}
      #   paths:
      #     - ./node_modules
      - run:
          name: Run Tests
          command: |
            phpunit --bootstrap php/adminReportSource.php tests/adminReportSourceTest
     branches:
      only:
        - unit_tests
        - master